package com.younes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.younes.util.TexttableCenter;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BOUKHTACHE
 */
public class BackupF extends javax.swing.JFrame {

    /**
     * Creates new form SalesF
     */
     ResultSet rst,rst1,rst2,rst3=null;
     PreparedStatement pst,pst1,pst2,pst3=null;
     Connection conn=null; 
     Calendar timer=Calendar.getInstance();
     SimpleDateFormat tim=new SimpleDateFormat("yyyy-MM-dd");
 
     JFrame frame ;
     int x,y;
     DefaultTableModel table ;  
    TexttableCenter tblcenter=new TexttableCenter();
    public BackupF() {
        initComponents();
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        icons();      
       // conn=JavaConnected.connectionDB();
       SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
              //jbarcode.requestFocus(); 
            } 
        });
       
       
        
    }
 /******info *******/
    private void icons(){
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/imgs.png")));
      } 
    private void setActuelColor(JLabel jtext) {
        jtext.setBackground(new Color(254, 0, 72));
    }

    private void setActuelColor2(JLabel jtext) {
        jtext.setBackground(new Color(94, 94, 94));
    }

    private void setResetColor2(JLabel jtext) {
        jtext.setBackground(new Color(17,17,50));
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpheader = new javax.swing.JPanel();
        jpanelclose = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jhide = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jmax = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jexit = new javax.swing.JLabel();
        jpanellogo = new javax.swing.JPanel();
        jpanelside1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jback = new javax.swing.JLabel();
        jpanelside2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpfooter = new javax.swing.JPanel();
        jpcontent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);

        jpheader.setPreferredSize(new java.awt.Dimension(1000, 50));
        jpheader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpheaderMouseDragged(evt);
            }
        });
        jpheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpheaderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpheaderMouseReleased(evt);
            }
        });
        jpheader.setLayout(new java.awt.BorderLayout());

        jpanelclose.setBackground(new java.awt.Color(17, 17, 50));
        jpanelclose.setPreferredSize(new java.awt.Dimension(150, 50));

        jPanel4.setBackground(new java.awt.Color(17, 17, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jhide.setBackground(new java.awt.Color(17, 17, 50));
        jhide.setForeground(new java.awt.Color(255, 255, 255));
        jhide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_minus_24px_1.png"))); // NOI18N
        jhide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhide.setOpaque(true);
        jhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jhideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jhideMouseExited(evt);
            }
        });
        jPanel4.add(jhide, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(17, 17, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jmax.setBackground(new java.awt.Color(17, 17, 50));
        jmax.setForeground(new java.awt.Color(255, 255, 255));
        jmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox_32px_7.png"))); // NOI18N
        jmax.setToolTipText("");
        jmax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmax.setOpaque(true);
        jmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmaxMouseExited(evt);
            }
        });
        jPanel3.add(jmax, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(17, 17, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jexit.setBackground(new java.awt.Color(17, 17, 50));
        jexit.setForeground(new java.awt.Color(255, 255, 255));
        jexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_close_window_32px.png"))); // NOI18N
        jexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexit.setOpaque(true);
        jexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jexitMouseExited(evt);
            }
        });
        jPanel2.add(jexit, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpanelcloseLayout = new javax.swing.GroupLayout(jpanelclose);
        jpanelclose.setLayout(jpanelcloseLayout);
        jpanelcloseLayout.setHorizontalGroup(
            jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcloseLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanelcloseLayout.setVerticalGroup(
            jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelcloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpheader.add(jpanelclose, java.awt.BorderLayout.LINE_END);

        jpanellogo.setBackground(new java.awt.Color(17, 17, 50));
        jpanellogo.setPreferredSize(new java.awt.Dimension(650, 50));

        jpanelside1.setBackground(new java.awt.Color(17, 17, 50));
        jpanelside1.setPreferredSize(new java.awt.Dimension(100, 50));

        jPanel5.setBackground(new java.awt.Color(17, 17, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jback.setBackground(new java.awt.Color(17, 17, 50));
        jback.setForeground(new java.awt.Color(255, 255, 255));
        jback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_forward_32px.png"))); // NOI18N
        jback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jback.setOpaque(true);
        jback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbackMouseExited(evt);
            }
        });
        jPanel5.add(jback, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpanelside1Layout = new javax.swing.GroupLayout(jpanelside1);
        jpanelside1.setLayout(jpanelside1Layout);
        jpanelside1Layout.setHorizontalGroup(
            jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelside1Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        jpanelside1Layout.setVerticalGroup(
            jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jpanelside2.setBackground(new java.awt.Color(17, 17, 50));
        jpanelside2.setPreferredSize(new java.awt.Dimension(150, 50));
        jpanelside2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(17, 17, 50));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_data_backup_32px_7.png"))); // NOI18N
        jLabel1.setText("تخزين البيانات");
        jLabel1.setOpaque(true);
        jpanelside2.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpanellogoLayout = new javax.swing.GroupLayout(jpanellogo);
        jpanellogo.setLayout(jpanellogoLayout);
        jpanellogoLayout.setHorizontalGroup(
            jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanellogoLayout.createSequentialGroup()
                .addComponent(jpanelside1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelside2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanellogoLayout.setVerticalGroup(
            jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanellogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelside1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelside2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpheader.add(jpanellogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpheader, java.awt.BorderLayout.PAGE_START);

        jpfooter.setBackground(new java.awt.Color(17, 17, 50));
        jpfooter.setMinimumSize(new java.awt.Dimension(100, 50));
        jpfooter.setPreferredSize(new java.awt.Dimension(1000, 50));

        javax.swing.GroupLayout jpfooterLayout = new javax.swing.GroupLayout(jpfooter);
        jpfooter.setLayout(jpfooterLayout);
        jpfooterLayout.setHorizontalGroup(
            jpfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jpfooterLayout.setVerticalGroup(
            jpfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jpfooter, java.awt.BorderLayout.PAGE_END);

        jpcontent.setBackground(new java.awt.Color(204, 204, 204));
        jpcontent.setPreferredSize(new java.awt.Dimension(1000, 600));
        jpcontent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpcontent.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jpcontent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseClicked
        this.setExtendedState(Home.ICONIFIED);
    }//GEN-LAST:event_jhideMouseClicked

    private void jhideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseEntered
        setActuelColor2(jhide);
    }//GEN-LAST:event_jhideMouseEntered

    private void jhideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseExited
        setResetColor2(jhide);
    }//GEN-LAST:event_jhideMouseExited

    private void jmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseClicked
        if (this.getExtendedState() != Home.MAXIMIZED_BOTH) {
            this.setExtendedState(Home.MAXIMIZED_BOTH);
            jmax.setIcon(new ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox2_32px_7.png")));
        } else {
            this.setExtendedState(Home.NORMAL);
            jmax.setIcon(new ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox_32px_7.png")));
        }
    }//GEN-LAST:event_jmaxMouseClicked

    private void jmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseEntered
        setActuelColor2(jmax);
    }//GEN-LAST:event_jmaxMouseEntered

    private void jmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseExited
        setResetColor2(jmax);
    }//GEN-LAST:event_jmaxMouseExited

    private void jexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseClicked
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "هل حقا تريد الخروج....!",
            "خروج",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_jexitMouseClicked

    private void jexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseEntered
        setActuelColor(jexit);
    }//GEN-LAST:event_jexitMouseEntered

    private void jexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseExited
        setResetColor2(jexit);
    }//GEN-LAST:event_jexitMouseExited

    private void jbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackMouseEntered
        setActuelColor(jback);
    }//GEN-LAST:event_jbackMouseEntered

    private void jbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackMouseExited
        setResetColor2(jback);
    }//GEN-LAST:event_jbackMouseExited

    private void jbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackMouseClicked
        this.dispose();
        Home hm=new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_jbackMouseClicked

    private void jpheaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpheaderMousePressed
        x = evt.getX();
        y = evt.getY();
        setOpacity((float) 0.7);
    }//GEN-LAST:event_jpheaderMousePressed

    private void jpheaderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpheaderMouseReleased
       setOpacity((float) 1.0);
    }//GEN-LAST:event_jpheaderMouseReleased

    private void jpheaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpheaderMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jpheaderMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackupF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackupF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackupF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackupF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackupF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jback;
    private javax.swing.JLabel jexit;
    private javax.swing.JLabel jhide;
    private javax.swing.JLabel jmax;
    private javax.swing.JPanel jpanelclose;
    private javax.swing.JPanel jpanellogo;
    private javax.swing.JPanel jpanelside1;
    private javax.swing.JPanel jpanelside2;
    private javax.swing.JPanel jpcontent;
    private javax.swing.JPanel jpfooter;
    private javax.swing.JPanel jpheader;
    // End of variables declaration//GEN-END:variables
}
