package com.younes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import com.younes.connection.CustomerDB;
import com.younes.connection.JavaConnected;
import com.younes.model.Customer;
import com.younes.util.TexttableCenter;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BOUKHTACHE
 */
public class CustomerForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeF
     */
     ResultSet rst,rst1=null;PreparedStatement pst,pst1=null;
      Connection conn=null;
   private JFrame frame;
   Customer cus=null;
  TexttableCenter tblcenter=new TexttableCenter();

  
    public CustomerForm() {
        initComponents();
        conn=JavaConnected.connectionDB();
        applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        showTableCustomer();
       SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
               jfirstname.requestFocus();
            } 
        });
    }

    private void showTableCustomer(){
        
        try{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("الرقم");
            model.addColumn("الإسم");
            model.addColumn("اللقب");
            model.addColumn("رفم  الهاتف");
            model.addColumn("العنوان");
            
            for(Customer cus:CustomerDB.getAllCustomer()){
                model.addRow(new Object[]{ cus.getCus_id(),cus.getFirstname(),
                cus.getLastname(),cus.getPhone(),cus.getAddress()});
            }
             jtable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
	     jtable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
             jtable.setRowHeight(20);
             jtable.setModel(model);
             
             for(int i=0;i<5;i++){
                 jtable.getColumnModel().getColumn(i).setCellRenderer(tblcenter);
             }
        }catch(Exception ex){ex.printStackTrace();   }
    }
    private void clearTable(){
        jid.setText("");jfirstname.setText("");jlastname.setText("");
        jphone.setText("");jaddress.setText("");
    }
        private boolean verifyField(){
        boolean calm=false;
        if(jfirstname.getText().trim().isEmpty()||jlastname.getText().trim().isEmpty()
           ||jphone.getText().trim().isEmpty()||jaddress.getText().trim().isEmpty()){
          return calm=true;  
        }
        return calm;
    }
    private void showInfoCustomer(){
        int row=jtable.getSelectedRow();
        if(row==-1){
         JOptionPane.showMessageDialog(null,"إختر العمود المناسب");
        }else{
        String Table_Click=(jtable.getModel().getValueAt(row, 0)).toString();
        int id=Integer.parseInt(Table_Click);
        Customer cus=CustomerDB.getCustomer(id);
        jid.setText(String.valueOf(cus.getCus_id()));
        jfirstname.setText(cus.getLastname());
        jlastname.setText(cus.getFirstname());
        jphone.setText(cus.getPhone());
        jaddress.setText(cus.getAddress());
        }
    }    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelheader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpanelfooter = new javax.swing.JPanel();
        jpanelcontent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jfirstname = new javax.swing.JTextField();
        jbclear = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jbsave = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jphone = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 600));

        jpanelheader.setBackground(new java.awt.Color(57, 59, 156));
        jpanelheader.setPreferredSize(new java.awt.Dimension(750, 50));
        jpanelheader.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(57, 59, 156));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelheader.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(57, 59, 156));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelheader.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(57, 59, 156));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(57, 59, 156));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("الزبائن");
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jpanelheader.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpanelheader, java.awt.BorderLayout.PAGE_START);

        jpanelfooter.setBackground(new java.awt.Color(204, 204, 204));
        jpanelfooter.setPreferredSize(new java.awt.Dimension(750, 50));

        javax.swing.GroupLayout jpanelfooterLayout = new javax.swing.GroupLayout(jpanelfooter);
        jpanelfooter.setLayout(jpanelfooterLayout);
        jpanelfooterLayout.setHorizontalGroup(
            jpanelfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jpanelfooterLayout.setVerticalGroup(
            jpanelfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jpanelfooter, java.awt.BorderLayout.PAGE_END);

        jpanelcontent.setBackground(new java.awt.Color(204, 204, 204));
        jpanelcontent.setPreferredSize(new java.awt.Dimension(750, 450));
        jpanelcontent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable.setBackground(new java.awt.Color(255, 255, 255));
        jtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtable.setForeground(new java.awt.Color(0, 0, 0));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtable.setPreferredSize(new java.awt.Dimension(400, 400));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 14, -1, 375));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("اللقب:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 50, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("رقم:");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 50, 30));

        jlastname.setBackground(new java.awt.Color(204, 204, 204));
        jlastname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlastname.setForeground(new java.awt.Color(0, 0, 0));
        jlastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jlastname.setCaretColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 125, 140, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("الإسم:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 50, 30));

        jid.setEditable(false);
        jid.setBackground(new java.awt.Color(204, 204, 204));
        jid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jid.setForeground(new java.awt.Color(0, 0, 0));
        jid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jid.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 45, 140, 30));

        jfirstname.setBackground(new java.awt.Color(204, 204, 204));
        jfirstname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jfirstname.setForeground(new java.awt.Color(0, 0, 0));
        jfirstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jfirstname.setCaretColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 85, 140, 30));

        jbclear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbclear.setForeground(new java.awt.Color(0, 0, 0));
        jbclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_broom_32px.png"))); // NOI18N
        jbclear.setText("تنظيف");
        jbclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearActionPerformed(evt);
            }
        });
        jPanel1.add(jbclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, 40));

        jbupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbupdate.setForeground(new java.awt.Color(0, 0, 0));
        jbupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_refresh_32px.png"))); // NOI18N
        jbupdate.setText("تحديث");
        jbupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, 40));

        jbsave.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbsave.setForeground(new java.awt.Color(0, 0, 0));
        jbsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_save_32px_1.png"))); // NOI18N
        jbsave.setText("حفظ");
        jbsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, 40));

        jbdelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbdelete.setForeground(new java.awt.Color(0, 0, 0));
        jbdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_waste_32px.png"))); // NOI18N
        jbdelete.setText("حذف");
        jbdelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("الهاتف:");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 60, 30));

        jphone.setBackground(new java.awt.Color(204, 204, 204));
        jphone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jphone.setForeground(new java.awt.Color(0, 0, 0));
        jphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jphone.setCaretColor(new java.awt.Color(0, 0, 0));
        jphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jphoneKeyTyped(evt);
            }
        });
        jPanel1.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 30));

        jaddress.setBackground(new java.awt.Color(204, 204, 204));
        jaddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jaddress.setForeground(new java.awt.Color(0, 0, 0));
        jaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jaddress.setCaretColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 140, 30));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("العنوان:");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 60, 30));

        jpanelcontent.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpanelcontent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 750, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
       String firstname=jfirstname.getText();String lastname=jlastname.getText();
       String phone=jphone.getText();String address=jaddress.getText();
       if(!verifyField()){
            cus=new Customer();
            cus.setFirstname(firstname);
            cus.setLastname(lastname);
            cus.setPhone(phone);
            cus.setAddress(address);
            int status=CustomerDB.save(cus);
            if(status>0){
                showTableCustomer();
                JOptionPane.showMessageDialog(null,"نجاح اخال المعلومات");
                clearTable();
            }else{
               JOptionPane.showMessageDialog(null,"خطأ إدخال البينات"); 
            }
       }else{
         JOptionPane.showMessageDialog(null,"أدخل البيانات...!");   
       }
       
    }//GEN-LAST:event_jbsaveActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
       String idcus=jid.getText();
       if(!idcus.trim().isEmpty()){
       int msg=JOptionPane.showConfirmDialog(null, "هل تريد حذف المعلومات..!","حذف",JOptionPane.YES_NO_OPTION);
      if(msg==0){
        int id=Integer.parseInt(jid.getText());
        int status=CustomerDB.delete(id);
            if(status>0){
                showTableCustomer();
                JOptionPane.showMessageDialog(null,"نجاح الحذف");
                clearTable();
            }else{
               JOptionPane.showMessageDialog(null,"خطأ إدخال البينات"); 
            }
        } }else{
         JOptionPane.showMessageDialog(null,"أدخل البيانات...!");   
       }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
       String firstname=jfirstname.getText();String lastname=jlastname.getText();
       String phone=jphone.getText();String address=jaddress.getText();
       String id=jid.getText();
        if(!id.trim().isEmpty()){
       if(!verifyField()){
            cus=new Customer();
            cus.setCus_id(Long.parseLong(id));
            cus.setFirstname(firstname);
            cus.setLastname(lastname);
            cus.setPhone(phone);
            cus.setAddress(address);
           
            int status=CustomerDB.update(cus);
            if(status>0){
                showTableCustomer();
                JOptionPane.showMessageDialog(null,"نجاح التحديث");
                clearTable();
            }else{
               JOptionPane.showMessageDialog(null,"خطأ إدخال البينات"); 
            }
       }else{
         JOptionPane.showMessageDialog(null,"أدخل البيانات...!");   
       } }else{
         JOptionPane.showMessageDialog(null,"أدخل البيانات...!");   
       }
        
    }//GEN-LAST:event_jbupdateActionPerformed

    private void jbclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearActionPerformed
        clearTable();
    }//GEN-LAST:event_jbclearActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
           showInfoCustomer();
    }//GEN-LAST:event_jtableMouseClicked

    private void jtableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
          showInfoCustomer(); 
       }
    }//GEN-LAST:event_jtableKeyPressed

    private void jtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
          showInfoCustomer(); 
        }
    }//GEN-LAST:event_jtableKeyReleased

    private void jphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jphoneKeyTyped
         char inumber = evt.getKeyChar();
        if (!(Character.isDigit(inumber))
            || (inumber == KeyEvent.VK_BACK_SPACE)
            || (inumber == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jphoneKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaddress;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbsave;
    private javax.swing.JButton jbupdate;
    private javax.swing.JTextField jfirstname;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jlastname;
    private javax.swing.JPanel jpanelcontent;
    private javax.swing.JPanel jpanelfooter;
    private javax.swing.JPanel jpanelheader;
    private javax.swing.JTextField jphone;
    private javax.swing.JTable jtable;
    // End of variables declaration//GEN-END:variables
}
