package com.younes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author BOUKHTACHE
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
        ResultSet rst, rst1 = null;
    PreparedStatement pst, pst1 = null;
    Connection conn = null;
    HomeF hf = new HomeF();
    int x, y;
    private JFrame frame;
    Calendar timer = Calendar.getInstance();
    SimpleDateFormat formt = new SimpleDateFormat("yyyy-MM-dd");
    Date todayt, todayNow = null;
    Date dtexpre, dtexpreN = null;
   
     
    public Home() {
        initComponents();
                 try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        icons();
        jDesktopPane1.add(hf).setVisible(true);
       
    }
  
private void icons(){
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/imgs.png")));
      } 
        public void setActuelColor(JLabel jtext) {
        jtext.setBackground(new Color(254, 0, 72));
    }

    public void setResetColor(JLabel jtext) {
        jtext.setBackground(new Color(7, 109, 228));
    }

    public void setActuelColor2(JLabel jtext) {
        jtext.setBackground(new Color(94, 94, 94));
    }

    public void setResetColor2(JLabel jtext) {
        jtext.setBackground(new Color(17,17,50));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jheader = new javax.swing.JPanel();
        jpanelclose = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jhide = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jmax = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jexit = new javax.swing.JLabel();
        jpanellogo = new javax.swing.JPanel();
        jpanelside1 = new javax.swing.JPanel();
        jpanelside2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpanelleft = new javax.swing.JPanel();
        jpanhome = new javax.swing.JPanel();
        jhome = new javax.swing.JLabel();
        jpanamin = new javax.swing.JPanel();
        jadmin = new javax.swing.JLabel();
        jpancustomer = new javax.swing.JPanel();
        jcustomer = new javax.swing.JLabel();
        jpstock = new javax.swing.JPanel();
        jstock = new javax.swing.JLabel();
        jpsales = new javax.swing.JPanel();
        jsales = new javax.swing.JLabel();
        jpinfoproducts = new javax.swing.JPanel();
        jinfoproducts = new javax.swing.JLabel();
        jpfact = new javax.swing.JPanel();
        jfact = new javax.swing.JLabel();
        jpsetting = new javax.swing.JPanel();
        jsetting = new javax.swing.JLabel();
        jpdetails = new javax.swing.JPanel();
        jdetails = new javax.swing.JLabel();
        jpabout = new javax.swing.JPanel();
        jabout = new javax.swing.JLabel();
        jpanelright = new javax.swing.JPanel();
        jpanelfooter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jheader.setBackground(new java.awt.Color(17, 17, 50));
        jheader.setMinimumSize(new java.awt.Dimension(24, 24));
        jheader.setName(""); // NOI18N
        jheader.setPreferredSize(new java.awt.Dimension(1000, 50));
        jheader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jheaderMouseDragged(evt);
            }
        });
        jheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jheaderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jheaderMouseReleased(evt);
            }
        });
        jheader.setLayout(new java.awt.BorderLayout());

        jpanelclose.setBackground(new java.awt.Color(17, 17, 50));
        jpanelclose.setPreferredSize(new java.awt.Dimension(150, 50));

        jPanel4.setBackground(new java.awt.Color(17, 17, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jhide.setBackground(new java.awt.Color(17, 17, 50));
        jhide.setForeground(new java.awt.Color(255, 255, 255));
        jhide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_minus_24px_1.png"))); // NOI18N
        jhide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhide.setOpaque(true);
        jhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jhideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jhideMouseExited(evt);
            }
        });
        jPanel4.add(jhide, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(17, 17, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jmax.setBackground(new java.awt.Color(17, 17, 50));
        jmax.setForeground(new java.awt.Color(255, 255, 255));
        jmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox_32px_7.png"))); // NOI18N
        jmax.setToolTipText("");
        jmax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmax.setOpaque(true);
        jmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmaxMouseExited(evt);
            }
        });
        jPanel3.add(jmax, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(17, 17, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jexit.setBackground(new java.awt.Color(17, 17, 50));
        jexit.setForeground(new java.awt.Color(255, 255, 255));
        jexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_close_window_32px.png"))); // NOI18N
        jexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexit.setOpaque(true);
        jexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jexitMouseExited(evt);
            }
        });
        jPanel2.add(jexit, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpanelcloseLayout = new javax.swing.GroupLayout(jpanelclose);
        jpanelclose.setLayout(jpanelcloseLayout);
        jpanelcloseLayout.setHorizontalGroup(
            jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcloseLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanelcloseLayout.setVerticalGroup(
            jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelcloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanelcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jheader.add(jpanelclose, java.awt.BorderLayout.LINE_END);

        jpanellogo.setBackground(new java.awt.Color(17, 17, 50));
        jpanellogo.setPreferredSize(new java.awt.Dimension(850, 50));

        jpanelside1.setBackground(new java.awt.Color(17, 17, 50));
        jpanelside1.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout jpanelside1Layout = new javax.swing.GroupLayout(jpanelside1);
        jpanelside1.setLayout(jpanelside1Layout);
        jpanelside1Layout.setHorizontalGroup(
            jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jpanelside1Layout.setVerticalGroup(
            jpanelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelside2.setBackground(new java.awt.Color(17, 17, 50));
        jpanelside2.setPreferredSize(new java.awt.Dimension(150, 50));
        jpanelside2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(17, 17, 50));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_online_store_32px.png"))); // NOI18N
        jLabel1.setText("سوبر ماركت");
        jLabel1.setOpaque(true);
        jpanelside2.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpanellogoLayout = new javax.swing.GroupLayout(jpanellogo);
        jpanellogo.setLayout(jpanellogoLayout);
        jpanellogoLayout.setHorizontalGroup(
            jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanellogoLayout.createSequentialGroup()
                .addComponent(jpanelside1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelside2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanellogoLayout.setVerticalGroup(
            jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanellogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelside1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelside2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jheader.add(jpanellogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jheader, java.awt.BorderLayout.PAGE_START);

        jpanelleft.setBackground(new java.awt.Color(7, 109, 228));
        jpanelleft.setPreferredSize(new java.awt.Dimension(150, 600));

        jpanhome.setBackground(new java.awt.Color(7, 109, 228));
        jpanhome.setPreferredSize(new java.awt.Dimension(150, 40));
        jpanhome.setLayout(new java.awt.BorderLayout());

        jhome.setBackground(new java.awt.Color(7, 109, 228));
        jhome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jhome.setForeground(new java.awt.Color(255, 255, 255));
        jhome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_home.png"))); // NOI18N
        jhome.setText("الرئيسية");
        jhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhome.setOpaque(true);
        jhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jhomeMouseExited(evt);
            }
        });
        jpanhome.add(jhome, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpanhome);

        jpanamin.setBackground(new java.awt.Color(7, 109, 228));
        jpanamin.setPreferredSize(new java.awt.Dimension(150, 40));
        jpanamin.setLayout(new java.awt.BorderLayout());

        jadmin.setBackground(new java.awt.Color(7, 109, 228));
        jadmin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jadmin.setForeground(new java.awt.Color(255, 255, 255));
        jadmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_user_32px.png"))); // NOI18N
        jadmin.setText("المدير");
        jadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jadmin.setOpaque(true);
        jadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jadminMouseExited(evt);
            }
        });
        jpanamin.add(jadmin, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpanamin);

        jpancustomer.setBackground(new java.awt.Color(7, 109, 228));
        jpancustomer.setPreferredSize(new java.awt.Dimension(150, 40));
        jpancustomer.setLayout(new java.awt.BorderLayout());

        jcustomer.setBackground(new java.awt.Color(7, 109, 228));
        jcustomer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcustomer.setForeground(new java.awt.Color(255, 255, 255));
        jcustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_guardian_32px.png"))); // NOI18N
        jcustomer.setText("الزبائن");
        jcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcustomer.setOpaque(true);
        jcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcustomerMouseExited(evt);
            }
        });
        jpancustomer.add(jcustomer, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpancustomer);

        jpstock.setBackground(new java.awt.Color(7, 109, 228));
        jpstock.setPreferredSize(new java.awt.Dimension(150, 40));
        jpstock.setLayout(new java.awt.BorderLayout());

        jstock.setBackground(new java.awt.Color(7, 109, 228));
        jstock.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jstock.setForeground(new java.awt.Color(255, 255, 255));
        jstock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_system_task_32px_1.png"))); // NOI18N
        jstock.setText("إدارة المخزون");
        jstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jstock.setOpaque(true);
        jstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jstockMouseExited(evt);
            }
        });
        jpstock.add(jstock, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpstock);

        jpsales.setBackground(new java.awt.Color(7, 109, 228));
        jpsales.setPreferredSize(new java.awt.Dimension(150, 40));
        jpsales.setLayout(new java.awt.BorderLayout());

        jsales.setBackground(new java.awt.Color(7, 109, 228));
        jsales.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jsales.setForeground(new java.awt.Color(255, 255, 255));
        jsales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_shopping_cart_32px_1.png"))); // NOI18N
        jsales.setText("إدارة المبيعات");
        jsales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsales.setOpaque(true);
        jsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jsalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsalesMouseExited(evt);
            }
        });
        jpsales.add(jsales, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpsales);

        jpinfoproducts.setBackground(new java.awt.Color(7, 109, 228));
        jpinfoproducts.setPreferredSize(new java.awt.Dimension(150, 40));
        jpinfoproducts.setLayout(new java.awt.BorderLayout());

        jinfoproducts.setBackground(new java.awt.Color(7, 109, 228));
        jinfoproducts.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jinfoproducts.setForeground(new java.awt.Color(255, 255, 255));
        jinfoproducts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jinfoproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_categorize_32px.png"))); // NOI18N
        jinfoproducts.setText("إدارة المنتجات");
        jinfoproducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jinfoproducts.setOpaque(true);
        jinfoproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jinfoproductsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jinfoproductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jinfoproductsMouseExited(evt);
            }
        });
        jpinfoproducts.add(jinfoproducts, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpinfoproducts);

        jpfact.setBackground(new java.awt.Color(7, 109, 228));
        jpfact.setPreferredSize(new java.awt.Dimension(150, 40));
        jpfact.setLayout(new java.awt.BorderLayout());

        jfact.setBackground(new java.awt.Color(7, 109, 228));
        jfact.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jfact.setForeground(new java.awt.Color(255, 255, 255));
        jfact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jfact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_file_invoice_dollar_32px.png"))); // NOI18N
        jfact.setText("إدارة الفواتير");
        jfact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jfact.setOpaque(true);
        jfact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jfactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jfactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jfactMouseExited(evt);
            }
        });
        jpfact.add(jfact, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpfact);

        jpsetting.setBackground(new java.awt.Color(7, 109, 228));
        jpsetting.setPreferredSize(new java.awt.Dimension(150, 40));
        jpsetting.setLayout(new java.awt.BorderLayout());

        jsetting.setBackground(new java.awt.Color(7, 109, 228));
        jsetting.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jsetting.setForeground(new java.awt.Color(255, 255, 255));
        jsetting.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_settings_32px.png"))); // NOI18N
        jsetting.setText("إعدادات");
        jsetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsetting.setOpaque(true);
        jsetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jsettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsettingMouseExited(evt);
            }
        });
        jpsetting.add(jsetting, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpsetting);

        jpdetails.setBackground(new java.awt.Color(7, 109, 228));
        jpdetails.setPreferredSize(new java.awt.Dimension(150, 40));
        jpdetails.setLayout(new java.awt.BorderLayout());

        jdetails.setBackground(new java.awt.Color(7, 109, 228));
        jdetails.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jdetails.setForeground(new java.awt.Color(255, 255, 255));
        jdetails.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_combo_chart_32px_1.png"))); // NOI18N
        jdetails.setText("بيانات المبيعات");
        jdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jdetails.setOpaque(true);
        jdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jdetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdetailsMouseExited(evt);
            }
        });
        jpdetails.add(jdetails, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpdetails);

        jpabout.setBackground(new java.awt.Color(7, 109, 228));
        jpabout.setPreferredSize(new java.awt.Dimension(150, 40));
        jpabout.setLayout(new java.awt.BorderLayout());

        jabout.setBackground(new java.awt.Color(7, 109, 228));
        jabout.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jabout.setForeground(new java.awt.Color(255, 255, 255));
        jabout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jabout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_high_importance_32px.png"))); // NOI18N
        jabout.setText("حول البرنامج");
        jabout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jabout.setOpaque(true);
        jabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jaboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jaboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jaboutMouseExited(evt);
            }
        });
        jpabout.add(jabout, java.awt.BorderLayout.CENTER);

        jpanelleft.add(jpabout);

        getContentPane().add(jpanelleft, java.awt.BorderLayout.LINE_START);

        jpanelright.setBackground(new java.awt.Color(17, 17, 50));
        jpanelright.setPreferredSize(new java.awt.Dimension(50, 600));

        javax.swing.GroupLayout jpanelrightLayout = new javax.swing.GroupLayout(jpanelright);
        jpanelright.setLayout(jpanelrightLayout);
        jpanelrightLayout.setHorizontalGroup(
            jpanelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jpanelrightLayout.setVerticalGroup(
            jpanelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jpanelright, java.awt.BorderLayout.LINE_END);

        jpanelfooter.setBackground(new java.awt.Color(17, 17, 50));
        jpanelfooter.setPreferredSize(new java.awt.Dimension(1000, 50));
        jpanelfooter.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(17, 17, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelfooter.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(17, 17, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelfooter.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(17, 17, 50));

        jLabel2.setBackground(new java.awt.Color(17, 17, 50));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("جميع الحقوق محفوظة ©");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanelfooter.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpanelfooter, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(750, 600));
        jDesktopPane1.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1000, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseClicked
         frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "هل حقا تريد الخروج....!",
                "خروج",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jexitMouseClicked

    private void jexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseEntered
        setActuelColor(jexit);
    }//GEN-LAST:event_jexitMouseEntered

    private void jexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseExited
        setResetColor2(jexit);
    }//GEN-LAST:event_jexitMouseExited

    private void jmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseClicked
        if (this.getExtendedState() != Home.MAXIMIZED_BOTH) {
            this.setExtendedState(Home.MAXIMIZED_BOTH);
            jmax.setIcon(new ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox2_32px_7.png")));
        } else {
            this.setExtendedState(Home.NORMAL);
            jmax.setIcon(new ImageIcon(getClass().getResource("/Pictures/icons8_unchecked_checkbox_32px_7.png")));
        }
    }//GEN-LAST:event_jmaxMouseClicked

    private void jmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseEntered
        setActuelColor2(jmax);
    }//GEN-LAST:event_jmaxMouseEntered

    private void jmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmaxMouseExited
       setResetColor2(jmax);
    }//GEN-LAST:event_jmaxMouseExited

    private void jhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseClicked
       this.setExtendedState(Home.ICONIFIED);
    }//GEN-LAST:event_jhideMouseClicked

    private void jhideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseEntered
        setActuelColor2(jhide);
    }//GEN-LAST:event_jhideMouseEntered

    private void jhideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhideMouseExited
        setResetColor2(jhide);
    }//GEN-LAST:event_jhideMouseExited

    private void jheaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jheaderMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jheaderMouseDragged

    private void jheaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jheaderMousePressed
        x = evt.getX();
        y = evt.getY();
        setOpacity((float) 0.7);
    }//GEN-LAST:event_jheaderMousePressed

    private void jheaderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jheaderMouseReleased
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jheaderMouseReleased

    private void jhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhomeMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        jDesktopPane1.add(hf).setVisible(true);
    }//GEN-LAST:event_jhomeMouseClicked

    private void jhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhomeMouseEntered
               setActuelColor(jhome);
    }//GEN-LAST:event_jhomeMouseEntered

    private void jhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhomeMouseExited
               setResetColor(jhome);
    }//GEN-LAST:event_jhomeMouseExited

    private void jadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadminMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        AdminForm adm=new AdminForm();
        jDesktopPane1.add(adm).setVisible(true);
         
    }//GEN-LAST:event_jadminMouseClicked

    private void jadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadminMouseEntered
              setActuelColor(jadmin);
    }//GEN-LAST:event_jadminMouseEntered

    private void jadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadminMouseExited
              setResetColor(jadmin);
    }//GEN-LAST:event_jadminMouseExited

    private void jcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcustomerMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        CustomerForm cus=new CustomerForm();
        jDesktopPane1.add(cus).setVisible(true);
    }//GEN-LAST:event_jcustomerMouseClicked

    private void jcustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcustomerMouseEntered
        setActuelColor(jcustomer);
    }//GEN-LAST:event_jcustomerMouseEntered

    private void jcustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcustomerMouseExited
        setResetColor(jcustomer);
    }//GEN-LAST:event_jcustomerMouseExited

    private void jstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstockMouseClicked
         jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        StockF stck=new StockF();
        jDesktopPane1.add(stck).setVisible(true);
    }//GEN-LAST:event_jstockMouseClicked

    private void jstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstockMouseEntered
       setActuelColor(jstock);
    }//GEN-LAST:event_jstockMouseEntered

    private void jstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstockMouseExited
         setResetColor(jstock);
    }//GEN-LAST:event_jstockMouseExited

    private void jsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsalesMouseClicked
        SalesF pf = new SalesF();
        this.dispose();
        pf.setVisible(true);
    }//GEN-LAST:event_jsalesMouseClicked

    private void jsalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsalesMouseEntered
        setActuelColor(jsales);
    }//GEN-LAST:event_jsalesMouseEntered

    private void jsalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsalesMouseExited
        setResetColor(jsales);
    }//GEN-LAST:event_jsalesMouseExited

    private void jinfoproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jinfoproductsMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        InfoProductF infp=new InfoProductF();
        jDesktopPane1.add(infp).setVisible(true);
    }//GEN-LAST:event_jinfoproductsMouseClicked

    private void jinfoproductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jinfoproductsMouseEntered
         setActuelColor(jinfoproducts);
    }//GEN-LAST:event_jinfoproductsMouseEntered

    private void jinfoproductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jinfoproductsMouseExited
        setResetColor(jinfoproducts);
    }//GEN-LAST:event_jinfoproductsMouseExited

    private void jfactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfactMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        InvoiceF inv=new InvoiceF();
        jDesktopPane1.add(inv).setVisible(true);
    }//GEN-LAST:event_jfactMouseClicked

    private void jfactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfactMouseEntered
       setActuelColor(jfact);
    }//GEN-LAST:event_jfactMouseEntered

    private void jfactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfactMouseExited
        setResetColor(jfact);
    }//GEN-LAST:event_jfactMouseExited

    private void jsettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsettingMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        SettingF setg=new SettingF();
        jDesktopPane1.add(setg).setVisible(true);
    }//GEN-LAST:event_jsettingMouseClicked

    private void jsettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsettingMouseEntered
       setActuelColor(jsetting);
    }//GEN-LAST:event_jsettingMouseEntered

    private void jsettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsettingMouseExited
      setResetColor(jsetting);
    }//GEN-LAST:event_jsettingMouseExited

    private void jaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaboutMouseClicked
         jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        AboutF about=new AboutF();
        jDesktopPane1.add(about).setVisible(true);
    }//GEN-LAST:event_jaboutMouseClicked

    private void jaboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaboutMouseEntered
       setActuelColor(jabout);
    }//GEN-LAST:event_jaboutMouseEntered

    private void jaboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaboutMouseExited
        setResetColor(jabout);
    }//GEN-LAST:event_jaboutMouseExited

    private void jdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdetailsMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
        DetailsF dtls=new DetailsF();
        jDesktopPane1.add(dtls).setVisible(true);         
    }//GEN-LAST:event_jdetailsMouseClicked

    private void jdetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdetailsMouseEntered
         setActuelColor(jdetails);
    }//GEN-LAST:event_jdetailsMouseEntered

    private void jdetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdetailsMouseExited
       setResetColor(jdetails);
    }//GEN-LAST:event_jdetailsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jabout;
    private javax.swing.JLabel jadmin;
    private javax.swing.JLabel jcustomer;
    private javax.swing.JLabel jdetails;
    private javax.swing.JLabel jexit;
    private javax.swing.JLabel jfact;
    private javax.swing.JPanel jheader;
    private javax.swing.JLabel jhide;
    private javax.swing.JLabel jhome;
    private javax.swing.JLabel jinfoproducts;
    private javax.swing.JLabel jmax;
    private javax.swing.JPanel jpabout;
    private javax.swing.JPanel jpanamin;
    private javax.swing.JPanel jpancustomer;
    private javax.swing.JPanel jpanelclose;
    private javax.swing.JPanel jpanelfooter;
    private javax.swing.JPanel jpanelleft;
    private javax.swing.JPanel jpanellogo;
    private javax.swing.JPanel jpanelright;
    private javax.swing.JPanel jpanelside1;
    private javax.swing.JPanel jpanelside2;
    private javax.swing.JPanel jpanhome;
    private javax.swing.JPanel jpdetails;
    private javax.swing.JPanel jpfact;
    private javax.swing.JPanel jpinfoproducts;
    private javax.swing.JPanel jpsales;
    private javax.swing.JPanel jpsetting;
    private javax.swing.JPanel jpstock;
    private javax.swing.JLabel jsales;
    private javax.swing.JLabel jsetting;
    private javax.swing.JLabel jstock;
    // End of variables declaration//GEN-END:variables
}
