package com.younes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import com.younes.connection.JavaConnected;
import com.younes.connection.JavaCreateDBS;
import com.younes.connection.UserDB;
import java.awt.ComponentOrientation;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author BOUKHTACHE
 */
public class SettingF extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeF
     */
    ResultSet rst, rst1 = null;
    PreparedStatement pst,pst0,pst1,pst2= null;
    Statement st=null;
    Connection conn,conn1,conn2,conn3 = null;
    String path,path2 = null;
    String filename=null;
    Calendar timer = Calendar.getInstance();
    SimpleDateFormat time = new SimpleDateFormat("yyyy-MM-dd");
    ByteArrayOutputStream bos = null;
    FileInputStream fis=null;
    byte[] pict = null;

  
    public SettingF() {
        initComponents();
         conn = JavaConnected.connectionDB();
        applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
    }

   
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelheader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpanelfooter = new javax.swing.JPanel();
        jpanelcontent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jgetfilesql = new javax.swing.JTextField();
        jbrestore = new javax.swing.JButton();
        jbackupsql = new javax.swing.JButton();
        jchoosefile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jerase = new javax.swing.JButton();
        jbtnuser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jclean = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 600));

        jpanelheader.setBackground(new java.awt.Color(57, 59, 156));
        jpanelheader.setPreferredSize(new java.awt.Dimension(750, 50));
        jpanelheader.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(57, 59, 156));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelheader.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(57, 59, 156));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jpanelheader.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(57, 59, 156));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(57, 59, 156));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_settings_32px.png"))); // NOI18N
        jLabel4.setText("الإعدادات");
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jpanelheader.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpanelheader, java.awt.BorderLayout.PAGE_START);

        jpanelfooter.setBackground(new java.awt.Color(204, 204, 204));
        jpanelfooter.setPreferredSize(new java.awt.Dimension(750, 50));

        javax.swing.GroupLayout jpanelfooterLayout = new javax.swing.GroupLayout(jpanelfooter);
        jpanelfooter.setLayout(jpanelfooterLayout);
        jpanelfooterLayout.setHorizontalGroup(
            jpanelfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jpanelfooterLayout.setVerticalGroup(
            jpanelfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jpanelfooter, java.awt.BorderLayout.PAGE_END);

        jpanelcontent.setBackground(new java.awt.Color(204, 204, 204));
        jpanelcontent.setPreferredSize(new java.awt.Dimension(750, 450));
        jpanelcontent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jgetfilesql.setBackground(new java.awt.Color(204, 204, 204));
        jgetfilesql.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jgetfilesql.setForeground(new java.awt.Color(0, 0, 0));
        jgetfilesql.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jgetfilesql.setCaretColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jgetfilesql, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 81, 370, -1));

        jbrestore.setBackground(new java.awt.Color(204, 204, 204));
        jbrestore.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbrestore.setForeground(new java.awt.Color(0, 0, 0));
        jbrestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_database_import_32px.png"))); // NOI18N
        jbrestore.setText("إستعادة");
        jbrestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbrestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrestoreActionPerformed(evt);
            }
        });
        jPanel1.add(jbrestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 120, -1, -1));

        jbackupsql.setBackground(new java.awt.Color(204, 204, 204));
        jbackupsql.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbackupsql.setForeground(new java.awt.Color(0, 0, 0));
        jbackupsql.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_database_export_32px.png"))); // NOI18N
        jbackupsql.setText("تخزين");
        jbackupsql.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbackupsql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackupsqlActionPerformed(evt);
            }
        });
        jPanel1.add(jbackupsql, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jchoosefile.setBackground(new java.awt.Color(204, 204, 204));
        jchoosefile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jchoosefile.setForeground(new java.awt.Color(0, 0, 0));
        jchoosefile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_file_explorer_32px.png"))); // NOI18N
        jchoosefile.setText("إختر الملف");
        jchoosefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jchoosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchoosefileActionPerformed(evt);
            }
        });
        jPanel1.add(jchoosefile, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 66, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_database_import_32px.png"))); // NOI18N
        jLabel3.setText("تخزين البيانات");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 17, 208, 37));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton.setForeground(new java.awt.Color(0, 0, 0));
        jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_refresh_32px.png"))); // NOI18N
        jButton.setText("تحديث");
        jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("كتابة البيانات:");
        jLabel5.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("حذف البينات:");
        jLabel1.setOpaque(true);

        jerase.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jerase.setForeground(new java.awt.Color(0, 0, 0));
        jerase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/trash.png"))); // NOI18N
        jerase.setText("مسح الكل");
        jerase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jerase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeraseActionPerformed(evt);
            }
        });

        jbtnuser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnuser.setForeground(new java.awt.Color(0, 0, 0));
        jbtnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_refresh_32px.png"))); // NOI18N
        jbtnuser.setText("تحديث");
        jbtnuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnuserActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("كتابة المسخدم:");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jerase)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jerase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnuser)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 220, 200));

        jclean.setBackground(new java.awt.Color(204, 204, 204));
        jclean.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jclean.setForeground(new java.awt.Color(0, 0, 0));
        jclean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8_broom_32px.png"))); // NOI18N
        jclean.setText("تنظيف");
        jclean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcleanActionPerformed(evt);
            }
        });
        jPanel1.add(jclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jpanelcontent.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpanelcontent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 750, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jbrestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrestoreActionPerformed

        String cmdsql = "C:/xampp/mysql/bin/mysql -u younes -p1234  -B marketbenackcha <"+path;
        Process p = null;
        if(jgetfilesql.getText().trim().isEmpty()||jgetfilesql.getText().equals(null)){
            JOptionPane.showMessageDialog(null, "إختر الملف!");
        }else{
            try {
                Runtime runtime = Runtime.getRuntime();
                p = runtime.exec(new String[]{"cmd.exe","/c",cmdsql});
                int processComplete = p.waitFor();
                if (processComplete == 0) {
                    JOptionPane.showMessageDialog(null, "نجاح الإستعادة!");
                } else {
                    JOptionPane.showMessageDialog(null, "فشل الإستعادة!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbrestoreActionPerformed

    private void jbackupsqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackupsqlActionPerformed
        Date dt = new Date();
        timer.setTime(dt);
        String dtm = time.format(timer.getTime());
        path = path + "_" + dtm + ".sql";
        Process p = null; //"rundll32 url.dll,FileProtocolHandler "+
        if(jgetfilesql.getText().trim().isEmpty()||jgetfilesql.getText().equals(null)){
            JOptionPane.showMessageDialog(null, "إختر الملف!");
        }else{
            try {
                Runtime runtime = Runtime.getRuntime(); // C:/wamp64/bin/mysql/mysql5.7.14/bin/mysqldump.exe
                String user="root";String pass="";
                String cmdsql="C:/xampp/mysql/bin/mysqldump -u younes -p1234  -B marketbenackcha -r "+path;
                p = runtime.exec(new String[]{"cmd.exe","/c",cmdsql});
                int processComplete = p.waitFor();
                if (processComplete == 0) {
                    JOptionPane.showMessageDialog(null, "نجاح التخزين!");
                } else {
                    JOptionPane.showMessageDialog(null, "فشل التخزين!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbackupsqlActionPerformed

    private void jchoosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchoosefileActionPerformed
        JFileChooser chooser = new JFileChooser();
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.SQL", "sql");
         chooser.addChoosableFileFilter(filter);
        int ap = chooser.showOpenDialog(null);
        if (ap == JFileChooser.APPROVE_OPTION){
            path2=chooser.getSelectedFile().getAbsolutePath();
        }else if(path2==null){
             JOptionPane.showMessageDialog(null, "إختر الملف!");
        }
         try {
                 File f = chooser.getSelectedFile();
                 path = f.getAbsolutePath();
                 path = path.replace('\\','/');
                 jgetfilesql.setText(path);  
                 
        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(null, "إختر الملف!");
          //  ex.printStackTrace();
        } 
        
    }//GEN-LAST:event_jchoosefileActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
      
        
       conn=JavaCreateDBS.connectionDBS();
       conn1=JavaConnected.connectionDB();
       conn2=UserDB.createUser(conn,st);
        JOptionPane.showMessageDialog(null, "نجاح كتابة البيانات!");

    }//GEN-LAST:event_jButtonActionPerformed

    private void jeraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeraseActionPerformed
        int msg=JOptionPane.showConfirmDialog(null, "Are you sure delete!","Delete DB",JOptionPane.WARNING_MESSAGE);
        if(msg==0){
            try{
                String query="drop database marketbenackcha";
                pst=conn.prepareStatement(query);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "نجاح مسح البيانات!") ;
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "خطأ مسح البيانات!") ;
            }
        }
    }//GEN-LAST:event_jeraseActionPerformed

    private void jbtnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnuserActionPerformed
         Process p = null;
        String cmd="C:/xampp/mysql/bin/mysql.exe --user=root --password= <"+path;
       if(jgetfilesql.getText().trim().isEmpty()||jgetfilesql.getText().equals(null)){
            JOptionPane.showMessageDialog(null, "إختر الملف!");
        }else{
    try {
        p=Runtime.getRuntime().exec(new String[]{"cmd.exe","/c",cmd});
     
          int processComplete = p.waitFor();
          if(processComplete==0){
              JOptionPane.showMessageDialog(null, "success creat user...!");
          }else{
             JOptionPane.showMessageDialog(null, "failed...!"); 
          }
          
    } catch (Exception ex) {
        ex.printStackTrace();
        
           }
       }
    }//GEN-LAST:event_jbtnuserActionPerformed

    private void jcleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcleanActionPerformed
       jgetfilesql.setText("");
    }//GEN-LAST:event_jcleanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbackupsql;
    private javax.swing.JButton jbrestore;
    private javax.swing.JButton jbtnuser;
    private javax.swing.JButton jchoosefile;
    private javax.swing.JButton jclean;
    private javax.swing.JButton jerase;
    private javax.swing.JTextField jgetfilesql;
    private javax.swing.JPanel jpanelcontent;
    private javax.swing.JPanel jpanelfooter;
    private javax.swing.JPanel jpanelheader;
    // End of variables declaration//GEN-END:variables
}
